### PR TITLE
Coloration tweaks for oil crafting + failed concoctions

### PR DESCRIPTION
**Pull request by Sunconure11**
See how well these look. Take pics for me since I’m not at a PC.

### CODE REVIEW

**Comment by MoriyaShiine** [comment]
I can't take pics for you without merging it. Send pictures when you're at your computer.

**Comment by Sunconure11** [comment]
Screenshot 2020-12-25 00 22 10

**Comment by Sunconure11** [comment]
Screenshot 2020-12-25 00 29 49

**Comment by Sunconure11** [comment]
Screenshot 2020-12-25 00 40 58

I think this is enough.

I altered Aqua Cerate, Cleansing Balm, Grim Elixir + Oil and Failure mode fluids.

Oil is now pink, for one thing, as intended.

**Comment by MoriyaShiine** [comment]
The Cleansing Balm color is way too faded, it should be significantly more yellow. Otherwise it looks great.

**Comment by Sunconure11** [comment]
Screenshot 2020-12-25 14 57 13
How is this?

**Comment by MoriyaShiine** [comment]
Still too pale.

**Comment by MoriyaShiine** [comment]
Look at the actual item for what color it should be.

**Comment by Sunconure11** [comment]
Screenshot 2020-12-25 15 06 44

**Pull request merged**
