### PR TITLE
Changed Elder Leaves + Sapling Textures

### PR DESCRIPTION
**Pull request by 3e2j**
The original textures have been a eyesore against their surroundings for long enough, this amends to changing the shade slightly of the leaves - not the texture base itself - see the image below for comparison
image

### CODE REVIEW

**Comment by 3e2j** [comment]
was made to imitate the type of leaves you would see in resource packs on birch trees, but not entirely copy the shade to not interrupt with the comparisons between the two types.
There's an image below for reference of why I figured this would look good.
image

**Comment by MoriyaShiine** [comment]
This is up to cyber to approve but she wants you to join the discord to discuss it

**Comment by cybercat5555** [comment]
Maybe less yellow idk
Elder trees don't seem to be yellow and this is not a birch tree

**Comment by 3e2j** [comment]
Less yellow? I understand it's not a birch tree, I can try to amend this but I need some clarification on 'less yellow', considering that the original texture is a pale yellow

**Comment by 3e2j** [comment]
I can darken it down via hue to have 'less yellow' if desired
NEW
image
OLD
image

**Comment by 3e2j** [comment]
Or I can try get it closer to an actual elder tree's leaf color
image

**Comment by 3e2j** [comment]
Old

New

**Comment by ThePinkpigeon** [comment]
hi is there anyway to get rid of demon pacts ?

**Comment by MoriyaShiine** [comment]
This pull request is quite literally years old and has absolutely nothing to do with what you're asking

**Pull request closed without merging**
