### PR TITLE
Add AllowVampireHeal and AllowVampireBurn event

### PR DESCRIPTION
**Pull request by williambl**
These events allow add-ons to cancel vampire burning/healing in arbitrary circumstances.

### CODE REVIEW

**Comment by williambl** [comment]
Wow, that was fast - thank you!

**Comment by MoriyaShiine** [comment]
Haha, no problem. I might wait a bit before a build in case any other issues show up.

**Comment by williambl** [comment]
I'm kinda forced to push the Haema update to now (because the old version is incompatible with the latest FAPI), would you be okay with pushing a Bewitchment update sooner?

**Comment by MoriyaShiine** [comment]
Let me fix the remaining issue and I'll make a build

**Comment by williambl** [comment]
Thanks!

**Comment by MoriyaShiine** [comment]
Released on github, on curseforge as soon as it's accepted

**Pull request merged**
